# Generated by Django 4.2.16 on 2025-12-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(default='Colombo', max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='MailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('recipient_name', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('regular', 'Regular')], default='regular', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_items', to='routes.address')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('optimized', 'Optimized'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('depot_latitude', models.FloatField(default=6.9271)),
                ('depot_longitude', models.FloatField(default=79.8612)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
                ('fuel_saving_percentage', models.FloatField(blank=True, null=True)),
                ('optimized_sequence', models.JSONField(blank=True, null=True)),
                ('baseline_sequence', models.JSONField(blank=True, null=True)),
                ('optimized_coordinates', models.JSONField(blank=True, null=True)),
                ('baseline_coordinates', models.JSONField(blank=True, null=True)),
                ('mail_items', models.ManyToManyField(related_name='routes', to='routes.mailitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('total_reward', models.FloatField()),
                ('epsilon', models.FloatField()),
                ('average_distance', models.FloatField()),
                ('training_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['episode'],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_start', models.CharField(max_length=255)),
                ('segment_end', models.CharField(max_length=255)),
                ('traffic_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('unknown', 'Unknown')], max_length=20)),
                ('delay_minutes', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='routes.route')),
            ],
            options={
                'verbose_name_plural': 'Traffic Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
